config/routes.rb
Rails.application.routes.draw do
	
  get 'sessions/new'

	root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login' , to: 'sessions#new'

  post '/login' , to: 'sessions#create'

  delete '/logout' , to: 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id , presence: true
  validates :content , presence: true , length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord

	has_many :microposts, dependent: :destroy

	attr_accessor :remember_token, :activation_token

	before_save :downcase_email  
	before_create :create_activation_digest

	validates :name, presence: true , length: { maximum: 20}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


	has_secure_password       
	validates :password, presence: true, length: { in: 6..20 } , allow_nil: true            


	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest,User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	#　激活账户
	def activate
		update_columns(activated: true, activated_at: Time.now)
	end

	# 发送激活邮件
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

private

		# 创建并赋值激活令牌和摘要
		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
		# 将大写email 转换成小写
		def downcase_email
			self.email = email.downcase
		end

	class << self

		def digest(string)		
			cost  = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
			BCrypt::Password.create(string, cost: cost)                                                  
		end
	
		def new_token
			SecureRandom.urlsafe_base64
		end	
	end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

	def edit
		@user = User.find_by(email: params[:email])
		if @user && !@user.activated? && @user.authenticated?(:activation, params[:id])
			@user.activate
			log_in @user
			flash[:success] = "Account activated!"
			redirect_to @user
		else
			flash[:danger] = "Account activation failed!"
			redirect_to root_url
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    log_out if logged_in? # or session[:user_id]
      
    redirect_to root_url
  end

  def create
  	# render html: params.inspect
  	@user = User.find_by(email: params[:session][:email].downcase)

  	if @user && @user.authenticate(params[:session][:password])
      # if @user.activated?
        log_in @user
        params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
  		  redirect_to @user
      # else
        # flash[:danger] = "用户不存在."
        # redirect_to login_url
      # end
  	else
  		flash.now[:danger] = 'Invalid email/password combination' 
  		render 'new'
  	end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user , only: [:edit, :update, :index, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def index
    # @users = User.where(activated: true).paginate(page: params[:page])
    @users = User.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    # redirect_to root_url and return unless @user.activated
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
  	@user = User.new(new_user_params)

  	if @user.save
      @user.send_activation_email
  		flash[:info] = "Please check your email to activate your account."
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(edit_user_params)
      flash[:success] = "Update successfully."
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  private
  	def new_user_params
  		params.require(:user).permit(:name,:email,:password,:password_confirmation)
 	 end

   def edit_user_params
      params.require(:user).permit(:name,:password,:password_confirmation)
   end

   def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."   
      redirect_to login_url
    end
   end

   def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = 'GetsuKami'
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# 重定向到存储的地址或者默认地址
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

# 存储后面需要使用的地址,只存储get请求的.
	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end

# log in user
	def log_in(user)
		session[:user_id] = user.id
	end

#return user in session(now)(unless without)
	def current_user
		if(user_id = session[:user_id]) # have user log in
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember , cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end	

# if user log in ,return true, else return false
	def logged_in?
 		!current_user.nil?
	end

# exit user
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

#remember user in session
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget # user.rb method # reset user table remember_digest nil
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id) #delete session
		@current_user = nil
	end

	def current_user?(user)
		user == current_user
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def get_form_hash(className,place)
		{ class: "#{className}" , placeholder: "#{place}" }
	end
	  # 返回指定用户的 Gravatar
  def gravatar_for(user, options = {size: 80} )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end
end

app/views/layouts/_background.html.erb
<%= link_to image_tag("home-hero.jpg", alt: "Zone Background", class: "background") %>

app/views/layouts/_default.html.erb
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a target="blank" href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a  target="blank" href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path , target: "_blank"  %></li>
      <li><%= link_to "Contact", contact_path ,target: "_blank" %></li>
      <li><a target: "blank" href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "GetsuKami", root_path , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path , target: "_blank" %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!-- call helper method, full_title get title -->
    <%= render 'layouts/default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <!-- <%= render 'layouts/background' %> -->
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
			<!--   <%= debug(params) if Rails.env.development? %> -->

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<%= link_to gravatar_for(micropost.user, size: 50) , micropost.user %>
	<span class="user"><%= link_to micropost.user.name , micropost.user %></span>
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %>
	</span>
</li>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>  
<!-- provide method will "Home" value assigment ':title' -->

<div class="center jumbotron">
	<h1>Welcome to GetsuKami Zone</h1>
	<p>  The Web 
  	<a href="https://github.com/GetsuKami/my-first-app.git" target="_blank">Code Source</a>
	</p>	

	<%= link_to "Sign Up Now!", signup_path  ,class: "btn btn-lg btn-primary" %>
</div>

<!-- 
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
	 -->

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to 'delete' , user, method: :delete, data: { confirm: "You sure?"} %>   
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title,"Update your profile") %>

<div class="form_row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' , readonly: true %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="gravatar_edit">
  <%= gravatar_for @user %><br \>
  <a href="http://gravatar.com/emails" target="_blank">change</a>
</div> 

<!-- 
 <%= link_to image_tag("123.png", alt: "Background_img",class: 'bsg-img',) %>
 -->

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  	<%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title,"Sign up") %>

<div class="form_row">
 	<div class="col-md-8 col-md-offset-3
  ">
   	<%= form_for(@user,url: signup_path) do |f| %> 
      <%= render 'shared/error_messages' %>
     	
      <%= f.text_field :name , get_form_hash("form-control","Enter name") %>
     	<%= f.email_field :email, get_form_hash("form-control","Enter email") %>
     	<%= f.password_field :password , get_form_hash("form-control","Password")%>
     	<%= f.password_field :password_confirmation,
                             get_form_hash("form-control","Password Confirmation") %>

     	<%= f.submit "Sign up for Zone", class: "btn btn-primary" %>
   	<% end %>
 	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title,@user.name) %>


<div class="show_row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
      </h1>
      <h1>
      	  <%= @user.name %>
      </h1>
    </section>
  </aside>
    <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>